name: thunderbird-extensions

on:
  push:
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    strategy:
      fail-fast: false
      matrix:
        nixpkgs:
          - nixos-20.03
          - master
        tbsync:
          - v2.11
          - master
        package:
          - thunderbird
          - thunderbird-with-extensions
          - enigmail
          - tbsync
          - dav-4-tbsync
          - eas-4-tbsync
          - autocrypt
          - sample-thunderbird

    steps:
    - name: Obtain maximum storage
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
        skip_adding_nixpkgs_channel: true
    - name: Nix config
      run: |
        sed -i 's/\(repo = "nixpkgs"; ref = \)"nixos-20.03"/\1"${{ matrix.nixpkgs }}"/' flake.nix
        sed -i 's/\(repo = "TbSync"; ref = \)"master"/\1"${{ matrix.tbsync }}"/' flake.nix
    - name: Nix build
      run: |
        nix-shell -p nixFlakes --run 'nix --experimental-features "flakes nix-command" build \
          --print-build-logs --recreate-lock-file .#packages.x86_64-linux.${{ matrix.package }}'
